# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leonardo/Workbench/neurowood-0.0.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leonardo/Workbench/neurowood-0.0.1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leonardo/Workbench/neurowood-0.0.1/CMakeFiles /home/leonardo/Workbench/neurowood-0.0.1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leonardo/Workbench/neurowood-0.0.1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Classifier

# Build rule for target.
Classifier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Classifier
.PHONY : Classifier

# fast build rule for target.
Classifier/fast:
	$(MAKE) -f CMakeFiles/Classifier.dir/build.make CMakeFiles/Classifier.dir/build
.PHONY : Classifier/fast

#=============================================================================
# Target rules for targets named Classifier_builder

# Build rule for target.
Classifier_builder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Classifier_builder
.PHONY : Classifier_builder

# fast build rule for target.
Classifier_builder/fast:
	$(MAKE) -f CMakeFiles/Classifier_builder.dir/build.make CMakeFiles/Classifier_builder.dir/build
.PHONY : Classifier_builder/fast

#=============================================================================
# Target rules for targets named Ftr_extractor

# Build rule for target.
Ftr_extractor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ftr_extractor
.PHONY : Ftr_extractor

# fast build rule for target.
Ftr_extractor/fast:
	$(MAKE) -f CMakeFiles/Ftr_extractor.dir/build.make CMakeFiles/Ftr_extractor.dir/build
.PHONY : Ftr_extractor/fast

#=============================================================================
# Target rules for targets named Im_processing

# Build rule for target.
Im_processing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Im_processing
.PHONY : Im_processing

# fast build rule for target.
Im_processing/fast:
	$(MAKE) -f CMakeFiles/Im_processing.dir/build.make CMakeFiles/Im_processing.dir/build
.PHONY : Im_processing/fast

#=============================================================================
# Target rules for targets named Model

# Build rule for target.
Model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Model
.PHONY : Model

# fast build rule for target.
Model/fast:
	$(MAKE) -f CMakeFiles/Model.dir/build.make CMakeFiles/Model.dir/build
.PHONY : Model/fast

#=============================================================================
# Target rules for targets named Model_trainer

# Build rule for target.
Model_trainer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Model_trainer
.PHONY : Model_trainer

# fast build rule for target.
Model_trainer/fast:
	$(MAKE) -f CMakeFiles/Model_trainer.dir/build.make CMakeFiles/Model_trainer.dir/build
.PHONY : Model_trainer/fast

#=============================================================================
# Target rules for targets named Teste

# Build rule for target.
Teste: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Teste
.PHONY : Teste

# fast build rule for target.
Teste/fast:
	$(MAKE) -f CMakeFiles/Teste.dir/build.make CMakeFiles/Teste.dir/build
.PHONY : Teste/fast

Classifier.o: Classifier.cpp.o
.PHONY : Classifier.o

# target to build an object file
Classifier.cpp.o:
	$(MAKE) -f CMakeFiles/Classifier.dir/build.make CMakeFiles/Classifier.dir/Classifier.cpp.o
.PHONY : Classifier.cpp.o

Classifier.i: Classifier.cpp.i
.PHONY : Classifier.i

# target to preprocess a source file
Classifier.cpp.i:
	$(MAKE) -f CMakeFiles/Classifier.dir/build.make CMakeFiles/Classifier.dir/Classifier.cpp.i
.PHONY : Classifier.cpp.i

Classifier.s: Classifier.cpp.s
.PHONY : Classifier.s

# target to generate assembly for a file
Classifier.cpp.s:
	$(MAKE) -f CMakeFiles/Classifier.dir/build.make CMakeFiles/Classifier.dir/Classifier.cpp.s
.PHONY : Classifier.cpp.s

Classifier_builder.o: Classifier_builder.cpp.o
.PHONY : Classifier_builder.o

# target to build an object file
Classifier_builder.cpp.o:
	$(MAKE) -f CMakeFiles/Classifier_builder.dir/build.make CMakeFiles/Classifier_builder.dir/Classifier_builder.cpp.o
.PHONY : Classifier_builder.cpp.o

Classifier_builder.i: Classifier_builder.cpp.i
.PHONY : Classifier_builder.i

# target to preprocess a source file
Classifier_builder.cpp.i:
	$(MAKE) -f CMakeFiles/Classifier_builder.dir/build.make CMakeFiles/Classifier_builder.dir/Classifier_builder.cpp.i
.PHONY : Classifier_builder.cpp.i

Classifier_builder.s: Classifier_builder.cpp.s
.PHONY : Classifier_builder.s

# target to generate assembly for a file
Classifier_builder.cpp.s:
	$(MAKE) -f CMakeFiles/Classifier_builder.dir/build.make CMakeFiles/Classifier_builder.dir/Classifier_builder.cpp.s
.PHONY : Classifier_builder.cpp.s

Ftr_extractor.o: Ftr_extractor.cpp.o
.PHONY : Ftr_extractor.o

# target to build an object file
Ftr_extractor.cpp.o:
	$(MAKE) -f CMakeFiles/Ftr_extractor.dir/build.make CMakeFiles/Ftr_extractor.dir/Ftr_extractor.cpp.o
.PHONY : Ftr_extractor.cpp.o

Ftr_extractor.i: Ftr_extractor.cpp.i
.PHONY : Ftr_extractor.i

# target to preprocess a source file
Ftr_extractor.cpp.i:
	$(MAKE) -f CMakeFiles/Ftr_extractor.dir/build.make CMakeFiles/Ftr_extractor.dir/Ftr_extractor.cpp.i
.PHONY : Ftr_extractor.cpp.i

Ftr_extractor.s: Ftr_extractor.cpp.s
.PHONY : Ftr_extractor.s

# target to generate assembly for a file
Ftr_extractor.cpp.s:
	$(MAKE) -f CMakeFiles/Ftr_extractor.dir/build.make CMakeFiles/Ftr_extractor.dir/Ftr_extractor.cpp.s
.PHONY : Ftr_extractor.cpp.s

Im_processing.o: Im_processing.cpp.o
.PHONY : Im_processing.o

# target to build an object file
Im_processing.cpp.o:
	$(MAKE) -f CMakeFiles/Im_processing.dir/build.make CMakeFiles/Im_processing.dir/Im_processing.cpp.o
.PHONY : Im_processing.cpp.o

Im_processing.i: Im_processing.cpp.i
.PHONY : Im_processing.i

# target to preprocess a source file
Im_processing.cpp.i:
	$(MAKE) -f CMakeFiles/Im_processing.dir/build.make CMakeFiles/Im_processing.dir/Im_processing.cpp.i
.PHONY : Im_processing.cpp.i

Im_processing.s: Im_processing.cpp.s
.PHONY : Im_processing.s

# target to generate assembly for a file
Im_processing.cpp.s:
	$(MAKE) -f CMakeFiles/Im_processing.dir/build.make CMakeFiles/Im_processing.dir/Im_processing.cpp.s
.PHONY : Im_processing.cpp.s

Model.o: Model.cpp.o
.PHONY : Model.o

# target to build an object file
Model.cpp.o:
	$(MAKE) -f CMakeFiles/Model.dir/build.make CMakeFiles/Model.dir/Model.cpp.o
.PHONY : Model.cpp.o

Model.i: Model.cpp.i
.PHONY : Model.i

# target to preprocess a source file
Model.cpp.i:
	$(MAKE) -f CMakeFiles/Model.dir/build.make CMakeFiles/Model.dir/Model.cpp.i
.PHONY : Model.cpp.i

Model.s: Model.cpp.s
.PHONY : Model.s

# target to generate assembly for a file
Model.cpp.s:
	$(MAKE) -f CMakeFiles/Model.dir/build.make CMakeFiles/Model.dir/Model.cpp.s
.PHONY : Model.cpp.s

Model_trainer.o: Model_trainer.cpp.o
.PHONY : Model_trainer.o

# target to build an object file
Model_trainer.cpp.o:
	$(MAKE) -f CMakeFiles/Model_trainer.dir/build.make CMakeFiles/Model_trainer.dir/Model_trainer.cpp.o
.PHONY : Model_trainer.cpp.o

Model_trainer.i: Model_trainer.cpp.i
.PHONY : Model_trainer.i

# target to preprocess a source file
Model_trainer.cpp.i:
	$(MAKE) -f CMakeFiles/Model_trainer.dir/build.make CMakeFiles/Model_trainer.dir/Model_trainer.cpp.i
.PHONY : Model_trainer.cpp.i

Model_trainer.s: Model_trainer.cpp.s
.PHONY : Model_trainer.s

# target to generate assembly for a file
Model_trainer.cpp.s:
	$(MAKE) -f CMakeFiles/Model_trainer.dir/build.make CMakeFiles/Model_trainer.dir/Model_trainer.cpp.s
.PHONY : Model_trainer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Teste.dir/build.make CMakeFiles/Teste.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Teste.dir/build.make CMakeFiles/Teste.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Teste.dir/build.make CMakeFiles/Teste.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Classifier"
	@echo "... Classifier_builder"
	@echo "... Ftr_extractor"
	@echo "... Im_processing"
	@echo "... Model"
	@echo "... Model_trainer"
	@echo "... Teste"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Classifier.o"
	@echo "... Classifier.i"
	@echo "... Classifier.s"
	@echo "... Classifier_builder.o"
	@echo "... Classifier_builder.i"
	@echo "... Classifier_builder.s"
	@echo "... Ftr_extractor.o"
	@echo "... Ftr_extractor.i"
	@echo "... Ftr_extractor.s"
	@echo "... Im_processing.o"
	@echo "... Im_processing.i"
	@echo "... Im_processing.s"
	@echo "... Model.o"
	@echo "... Model.i"
	@echo "... Model.s"
	@echo "... Model_trainer.o"
	@echo "... Model_trainer.i"
	@echo "... Model_trainer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

